#page title
page_title                                : InstantCoder                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1067517686                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : InstantCoder                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free with In-App Purchases                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : You are the best developer in the world and you would like to code anytime, anywhere. InstantCoder makes it possible for you to edit and review code on your lovely iPhone and iPad.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Shumin Sun                                
your_link                                 : https://marknoteapp.com                     
your_city                                 :                                 
email_address                             : marknoteapps@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : markmarknote
github_username                           : marknote
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Syntax highlighting
    description                           : "All mainstream programming languages: css, js, html, swift, objective-c, c/c++, java, python, R, etc"
    fontawesome_icon_name                 : magic

  - title                                 : Run your code snippet
    description                           : "You can run code snippets in js, java, r, python 3, c/c++, lua and ruby and see the result"
    fontawesome_icon_name                 : plane
    
  - title                                 : Autosave changes
    description                           : You focus on coding and the app tracks the changes
    fontawesome_icon_name                 : clock

  - title                                 : Realtime preview
    description                           : Code and see the effect immediately
    fontawesome_icon_name                 : adjust
  
  - title                                 : Open file system
    description                           : You can open and view your data in other apps
    fontawesome_icon_name                 : star

  - title                                 : Web uploader
    description                           : Upload and download files with HTTP directly to and from your devices.
    fontawesome_icon_name                 : mobile

  - title                                 : Sync with Cloud
    description                           : Sync your source code among multiple devices via the Cloud service you choose
    fontawesome_icon_name                 : sync

  - title                                 : Terminal and SSH
    description                           : A terminal is provided with minimal set of commands, include SSH enables logging to a remote machine
    fontawesome_icon_name                 : terminal




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
# markdown: kramdown
markdown: redcarpet
redcarpet:
      extensions: [with_toc_data]
